/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* Thu Jun 27 10:35:31 2013 */

/* parameterized module instance */
ram_dq __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), 
    .Data( ), .Q( ));
