/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* C:\lscc\diamond\2.2\ispfpga\bin\nt\scuba.exe -w -n ram_dq -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type bram -wp 10 -rp 1000 -addr_width 9 -data_width 16 -num_rows 512 -writemode NORMAL -cascade 11 -e  */
/* Thu Jun 27 10:35:31 2013 */


`timescale 1 ns / 1 ps
module ram_dq (Clock, ClockEn, Reset, WE, Address, Data, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClockEn;
    input wire Reset;
    input wire WE;
    input wire [8:0] Address;
    input wire [15:0] Data;
    output wire [15:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam ram_dq_0_0_0_0.CSDECODE_B = "0b111" ;
    defparam ram_dq_0_0_0_0.CSDECODE_A = "0b000" ;
    defparam ram_dq_0_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam ram_dq_0_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam ram_dq_0_0_0_0.GSR = "DISABLED" ;
    defparam ram_dq_0_0_0_0.REGMODE_B = "NOREG" ;
    defparam ram_dq_0_0_0_0.REGMODE_A = "NOREG" ;
    defparam ram_dq_0_0_0_0.DATA_WIDTH_B = 18 ;
    defparam ram_dq_0_0_0_0.DATA_WIDTH_A = 18 ;
    DP16KC ram_dq_0_0_0_0 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(Data[9]), .DIA10(Data[10]), 
        .DIA11(Data[11]), .DIA12(Data[12]), .DIA13(Data[13]), .DIA14(Data[14]), 
        .DIA15(Data[15]), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vhi), 
        .ADA1(scuba_vhi), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(Address[0]), 
        .ADA5(Address[1]), .ADA6(Address[2]), .ADA7(Address[3]), .ADA8(Address[4]), 
        .ADA9(Address[5]), .ADA10(Address[6]), .ADA11(Address[7]), .ADA12(Address[8]), 
        .ADA13(scuba_vlo), .CEA(ClockEn), .CLKA(Clock), .OCEA(ClockEn), 
        .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), 
        .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(scuba_vlo), 
        .ADB5(scuba_vlo), .ADB6(scuba_vlo), .ADB7(scuba_vlo), .ADB8(scuba_vlo), 
        .ADB9(scuba_vlo), .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), 
        .ADB13(scuba_vlo), .CEB(scuba_vhi), .CLKB(scuba_vlo), .OCEB(scuba_vhi), 
        .WEB(scuba_vlo), .CSB0(scuba_vlo), .CSB1(scuba_vlo), .CSB2(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA0(Q[0]), .DOA1(Q[1]), .DOA2(Q[2]), .DOA3(Q[3]), 
        .DOA4(Q[4]), .DOA5(Q[5]), .DOA6(Q[6]), .DOA7(Q[7]), .DOA8(Q[8]), 
        .DOA9(Q[9]), .DOA10(Q[10]), .DOA11(Q[11]), .DOA12(Q[12]), .DOA13(Q[13]), 
        .DOA14(Q[14]), .DOA15(Q[15]), .DOA16(), .DOA17(), .DOB0(), .DOB1(), 
        .DOB2(), .DOB3(), .DOB4(), .DOB5(), .DOB6(), .DOB7(), .DOB8(), .DOB9(), 
        .DOB10(), .DOB11(), .DOB12(), .DOB13(), .DOB14(), .DOB15(), .DOB16(), 
        .DOB17())
             /* synthesis MEM_LPC_FILE="ram_dq.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;



    // exemplar begin
    // exemplar attribute ram_dq_0_0_0_0 MEM_LPC_FILE ram_dq.lpc
    // exemplar attribute ram_dq_0_0_0_0 MEM_INIT_FILE 
    // exemplar attribute ram_dq_0_0_0_0 RESETMODE SYNC
    // exemplar end

endmodule
