/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* Fri Jun 28 20:58:35 2013 */

/* parameterized module instance */
ram_dq __ (.Clock( ), .ClockEn( ), .Reset( ), .ByteEn( ), .WE( ), 
    .Address( ), .Data( ), .Q( ));
