/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.1 */
/* Sat Apr 05 17:46:50 2014 */

/* parameterized module instance */
biosrom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
